# GitHub Dependabot configuration for automated dependency updates
# Updates are reviewed manually to ensure security

version: 2
updates:
  # Monitor GitHub Actions for security updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "prasincs"
    commit-message:
      prefix: "security"
      include: "scope"

  # Note: Swift Package Manager support would go here when Dependabot adds it
  # For now, we manually monitor Swift dependencies