name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  security:
    name: Security Checks
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for gitleaks
    
    - name: Verify Dependencies
      run: |
        chmod +x scripts/verify-dependencies.sh
        scripts/verify-dependencies.sh
    
    - name: Check for secrets
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      with:
        config-path: .gitleaks.toml
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      if: github.event_name == 'pull_request'
      with:
        fail-on-severity: moderate
  test:
    name: Test on macOS
    runs-on: macos-latest
    needs: security
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
    
    - name: Swift version
      run: swift --version
    
    - name: Build
      run: make build
    
    - name: Run tests
      run: make test
    
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-22.04
    needs: security

    steps:
    - uses: actions/checkout@v4

    - name: Install Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'

    - name: Swift version
      run: swift --version

    - name: Run tests
      run: swift test

  release-build:
    name: Release Build
    runs-on: macos-latest
    needs: security
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
    
    - name: Build Release
      run: make release
    
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: ClipboardHistory-macOS
        path: ClipboardHistory.app
        
  lint:
    name: SwiftLint
    runs-on: macos-latest
    needs: security
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: make lint || true